# Generated by Django 4.1.4 on 2022-12-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_agent_master_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_data',
            old_name='contact_status',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='file_data',
            old_name='level_one',
            new_name='is_processed',
        ),
        migrations.RemoveField(
            model_name='file_data',
            name='level_two',
        ),
    ]
