# Generated by Django 4.1.4 on 2023-01-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_file_data_xl_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_master',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='agent_master',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file_data',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
